version: "3.4"

services:
    server:
        image: golang-template-project:debug
        build:
            context: .
            dockerfile: Dockerfile
            target: debug
        ports:
            - 8080:8080
            - 40000:40000
        env_file: app.env
        environment:
            - SERVER_PORT
        volumes:
            - .:/golang-template-project

    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
        ports:
            - "3307:3306"
        volumes:
            - /tmp/mysql-data:/var/lib/mysql